
services:
  db:
    image: pgvector/pgvector:pg17
    container_name: meli_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql:ro

  # ⚙️ FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - LOCAL_MODE=si
      - PYTHONUNBUFFERED=1


volumes:
  pgdata:
