
services:
  db:
    image: pgvector/pgvector:pg17
    container_name: meli_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      #- ./data/files/backup_many.sql:/docker-entrypoint-initdb.d/backup.sql:ro

  # ⚙️ FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - ./backend/prod-cred.json:/app/prod-cred.json:ro
      - ./data:/data
    environment:
      - DB_HOST=db
      - GOOGLE_APPLICATION_CREDENTIALS=/app/prod-cred.json
      - APP_ENVIRONMENT=local
      - LOCAL_MODE=si
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # 🌐 Vite Frontend (production preview)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
      

    environment:
      - NODE_ENV=development

volumes:
  pgdata:
