"""update datatime type

Revision ID: 004f9490733f
Revises: 00160309d083
Create Date: 2026-01-20 22:43:34.390119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '004f9490733f'
down_revision: Union[str, None] = '00160309d083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('answer', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('answer', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               comment='unique identifier for the entity',
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_answer_id'), 'answer', ['id'], unique=False)
    op.alter_column('assessment', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('assessment', 'finished_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('assessment', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('assessment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('assessment', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               comment='unique identifier for the entity',
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_assessment_id'), 'assessment', ['id'], unique=False)
    op.alter_column('feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('feedback', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('feedback', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               comment='unique identifier for the entity',
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.alter_column('option', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('option', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('option', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               comment='unique identifier for the entity',
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_option_id'), 'option', ['id'], unique=False)
    op.alter_column('question', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('question', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('question', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               comment='unique identifier for the entity',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('question_id_seq'::regclass)"))
    op.create_index(op.f('ix_question_id'), 'question', ['id'], unique=False)
    op.alter_column('survey', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('survey', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('survey', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               comment='unique identifier for the entity',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('survey_id_seq'::regclass)"))
    op.create_index(op.f('ix_survey_id'), 'survey', ['id'], unique=False)
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('user', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               comment='unique identifier for the entity',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('user_id_seq'::regclass)"))
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.alter_column('user', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               comment=None,
               existing_comment='unique identifier for the entity',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('user_id_seq'::regclass)"))
    op.alter_column('user', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_survey_id'), table_name='survey')
    op.alter_column('survey', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               comment=None,
               existing_comment='unique identifier for the entity',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('survey_id_seq'::regclass)"))
    op.alter_column('survey', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('survey', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_question_id'), table_name='question')
    op.alter_column('question', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               comment=None,
               existing_comment='unique identifier for the entity',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('question_id_seq'::regclass)"))
    op.alter_column('question', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('question', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_option_id'), table_name='option')
    op.alter_column('option', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               comment=None,
               existing_comment='unique identifier for the entity',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('option', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('option', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.alter_column('feedback', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               comment=None,
               existing_comment='unique identifier for the entity',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('feedback', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('feedback', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_assessment_id'), table_name='assessment')
    op.alter_column('assessment', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               comment=None,
               existing_comment='unique identifier for the entity',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('assessment', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('assessment', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('assessment', 'finished_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('assessment', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_answer_id'), table_name='answer')
    op.alter_column('answer', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               comment=None,
               existing_comment='unique identifier for the entity',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('answer', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('answer', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
