"""add hint column

Revision ID: 309edd015d9e
Revises: 004f9490733f
Create Date: 2026-01-21 00:19:16.189489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '309edd015d9e'
down_revision: Union[str, None] = '004f9490733f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'is_correct')
    op.drop_column('answer', 'score')
    op.add_column('question', sa.Column('hint', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'hint')
    op.add_column('answer', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
